require.config({
    paths: {
        'picLazyLoad':'picLazyLoad',
        'webuploader':'webuploader',
        'index': 'module/index',
        'accountList': 'module/accountList',
        'cityPicker': 'sm-city-picker',
        'address': 'module/address',
        'applyShop': 'module/applyShop',
        'assess': 'module/assess',
        'balance': 'module/balance',
        'cart': 'module/cart',
        'family': 'module/family',
        'findPassword': 'module/find_password',
        'joinMember': 'module/joinmember',
        'letterBox': 'module/letter_box',
        'login': 'module/login',
        'logistics': 'module/logistics',
        'member': 'module/member',
        'modifyInfo': 'module/modify_info',
        'modifyPassowrd': 'module/modify_password',
        'order': 'module/order',
        'orderInfo':'module/order_info',
        'passd': 'module/passd',
        'product': 'module/product',
        'productComment': 'module/product_comment',
        'productCategories': 'module/productCategories',
        'productContent': 'module/productContent',
        'productList': 'module/productList',
        'qr': 'module/qr',
        'regist': 'module/regist',
        'recharge': 'module/recharge',
        'replacephone': 'module/replacephone',
        'safety': 'module/safety',
        'shopQr': 'module/shop_qr',
        'shopAddress': 'module/shopAddress',
        'shopManager': 'module/shopManager',
        'shopInfoUpdate': 'module/shopInfoUpdate',
        'shopSelectProduct': 'module/shopSelectProduct',
        'submitOrder': 'module/submitOrder',
        'tradepay': 'module/tradepay',
        'userinfo': 'module/userinfo',
        'userInformation': 'module/userInformation',
        'search': 'module/search',
        'shopInfoUpdate':'module/shopInfoUpdate',
        'jweixin':'module/jweixin-1.0.0',
        'weixinConfig':'module/weixin.config',
        'cookie':'module/jquery.cookie',
        'achievement':'module/achievement',
        'shopProductManage':'module/shopProductManage',
        'shopProductDetail':'module/shopProductDetail',
        'shopProductDetailManage':'module/shopProductDetailManage',
        'shopProductCreate':'module/shopProductCreate',
        'afterSales':'module/after_sales',
        'shopManageAdd':'module/shopManageAdd',
        'letterDetail':'module/letter_detail',
        'letter':'module/letter',
        'openShop':'module/open_shop',
        'consume_records':'module/consume_records_detail',
        'shopCategoryManage':'module/shopCategoryManage',
        'shopOrderManage':'module/shopOrderManage',
        'shopMsg':'module/shopMsg',
        'delivery':'module/delivery',
        'shop_order_info':'module/shop_order_info',
        'selectIcon':'module/selectIcon',
        'shopSonCateAdd':'module/shopSonCateAdd',
        'shipping':'module/shipping',
        'shop_product_classify':'module/shop_product_classify',
        'present_manner':'module/present_manner',
        'present_record':'module/present_record'
    },
    urlArgs: "ver=" +  (new Date()).getTime(), 
    waitSeconds: 0
});

require(['picLazyLoad','weixinConfig','index','cookie', 'login', 'member', 'accountList','cityPicker', 'address', 'applyShop', 'assess', 'balance', 'cart', 'family', 'findPassword', 'joinMember', 'letterBox', 'logistics', 'modifyInfo', 'modifyPassowrd', 'order', 'orderInfo', 'passd', 'product', 'productComment', 'productCategories', 'productContent', 'productList', 'qr', 'regist', 'recharge', 'replacephone', 'safety', 'shopQr', 'shopAddress', 'shopManager', 'shopSelectProduct', 'submitOrder', 'tradepay', 'userinfo', 'userInformation', 'search','shopInfoUpdate','jweixin','achievement','shopInfoUpdate','shopProductManage','shopProductDetail','shopProductDetailManage','shopProductCreate','afterSales','shopManageAdd','letterDetail','letter','openShop','consume_records','shopCategoryManage','shopMsg','shopOrderManage','delivery','shop_order_info','selectIcon','shopSonCateAdd','shipping','shop_product_classify','present_manner','present_record'], function() {
      $.init();
});
